### ISSUE TITLE
Rariety not working as intended?

### ISSUE THREAD

**Issue by RickWillcox** [AgentFUD/agentfud-art-engine#20]
When setting rarity in rariety-config.json I assume the higher the number relative to the other numbers for more weight that rarity has.

But as you can see here it doesnt seem to do anything.
![image](https://user-images.githubusercontent.com/53924507/146535121-1a198115-0050-4cf6-9cec-fd12b862a6cc.png)

Am I doing something wrong with this?

Also cool script mate

**Comment by RickWillcox** [comment]
Ah nvm just found the 1/2/3/ settings.

**Comment by AgentFUD** [comment]
@RickWillcox Yeah, it is important to set up your DNA generation strategy properly in your instance_config.py
Maybe I should make it clear in the documentation.
